name: frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run yarn install, check and build
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn install
          yarn run check
          yarn run build
        working-directory: html
      - name: Upload frontend header artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-header
          path: src/html.h
