name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-mod"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/ttyd-*.tar.gz
          fail_on_unmatched_files: true

  update-tap:
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Check out tap repository
        uses: actions/checkout@v5
        with:
          repository: twio142/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Generate formula file
        run: |
          cd homebrew-tap
          VERSION="${{ github.ref_name }}"
          TEMPLATE_FILE="Formula/ttyd.rb.template"
          FORMULA_FILE="Formula/ttyd.rb"
          sed -e "s/%%VERSION%%/${VERSION#v}/g" \
              -e "s/%%SHA_ARM64_MACOS%%/${{ needs.build.outputs.SHA256_arm64_macos }}/g" \
              -e "s/%%SHA_X86_64_MACOS%%/${{ needs.build.outputs.SHA256_x86_64_macos }}/g" \
              -e "s/%%SHA_X86_64_LINUX%%/${{ needs.build.outputs.SHA256_x86_64_linux }}/g" \
              ${TEMPLATE_FILE} > ${FORMULA_FILE}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          path: homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          commit-message: "chore: bump ttyd to ${{ github.ref_name }}"
          title: "Bump ttyd to ${{ github.ref_name }}"
          body: "Automated release for ttyd version ${{ github.ref_name }}"
          branch: "bump-ttyd-${{ github.ref_name }}"
          base: main
          delete-branch: true
          add-paths: "Formula/ttyd.rb"
